"""initial schema

Revision ID: d2efd85930d0
Revises: 
Create Date: 2026-03-17 19:57:07.868587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2efd85930d0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('subscription_tier', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('asset_type', sa.Enum('JETSKI', 'BOAT', 'PARASAIL', 'OTHER', name='asset_type', create_constraint=True), nullable=False),
    sa.Column('identifier', sa.String(length=100), nullable=False, comment='Hull number, registration, serial, etc.'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Arbitrary equipment metadata (year, make, model, colour, etc.)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_identifier'), 'assets', ['identifier'], unique=False)
    op.create_index(op.f('ix_assets_tenant_id'), 'assets', ['tenant_id'], unique=False)
    op.create_table('model_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False, comment='Identifier for the Anthropic model or prompt version used'),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_inspections', sa.Integer(), nullable=False),
    sa.Column('total_findings', sa.Integer(), nullable=False),
    sa.Column('true_positives', sa.Integer(), nullable=False),
    sa.Column('false_positives', sa.Integer(), nullable=False),
    sa.Column('false_negatives', sa.Integer(), nullable=False),
    sa.Column('precision', sa.Float(), nullable=True),
    sa.Column('recall', sa.Float(), nullable=True),
    sa.Column('f1_score', sa.Float(), nullable=True),
    sa.Column('avg_confidence', sa.Float(), nullable=True),
    sa.Column('severity_accuracy', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Breakdown of accuracy per severity level'),
    sa.Column('damage_type_accuracy', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Breakdown of accuracy per damage type'),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_metrics_tenant_id'), 'model_metrics', ['tenant_id'], unique=False)
    op.create_table('repair_cost_lookups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False, comment='Matches AssetType enum values: jetski, boat, parasail, other'),
    sa.Column('damage_type', sa.String(length=100), nullable=False, comment='e.g. scratch, dent, crack, tear'),
    sa.Column('severity', sa.String(length=50), nullable=False, comment='Matches DamageSeverity enum values: minor, moderate, major, severe'),
    sa.Column('min_cost', sa.Float(), nullable=False),
    sa.Column('max_cost', sa.Float(), nullable=False),
    sa.Column('avg_cost', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'asset_type', 'damage_type', 'severity', name='uq_repair_cost_lookup')
    )
    op.create_index(op.f('ix_repair_cost_lookups_tenant_id'), 'repair_cost_lookups', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'OPERATOR', 'VIEWER', name='user_role', create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('rental_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('renter_name', sa.String(length=255), nullable=False),
    sa.Column('renter_contact', sa.String(length=320), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'DISPUTED', name='rental_session_status', create_constraint=True), nullable=False),
    sa.Column('pre_inspection_id', sa.UUID(), nullable=True),
    sa.Column('post_inspection_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['post_inspection_id'], ['inspections.id'], use_alter=True),
    sa.ForeignKeyConstraint(['pre_inspection_id'], ['inspections.id'], use_alter=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rental_sessions_asset_id'), 'rental_sessions', ['asset_id'], unique=False)
    op.create_index(op.f('ix_rental_sessions_tenant_id'), 'rental_sessions', ['tenant_id'], unique=False)
    op.create_table('inspections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('rental_session_id', sa.UUID(), nullable=True),
    sa.Column('inspection_type', sa.Enum('PRE_RENTAL', 'POST_RENTAL', name='inspection_type', create_constraint=True), nullable=False),
    sa.Column('inspector_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('location_lat', sa.Float(), nullable=True),
    sa.Column('location_lng', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ANALYZING', 'REVIEWED', 'APPROVED', name='inspection_status', create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rental_session_id'], ['rental_sessions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspections_asset_id'), 'inspections', ['asset_id'], unique=False)
    op.create_index(op.f('ix_inspections_rental_session_id'), 'inspections', ['rental_session_id'], unique=False)
    op.create_index(op.f('ix_inspections_tenant_id'), 'inspections', ['tenant_id'], unique=False)
    op.create_table('photos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inspection_id', sa.UUID(), nullable=False),
    sa.Column('r2_key', sa.String(length=1024), nullable=False, comment='Object key in R2 — never store full URLs'),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Camera settings, dimensions, quality_score, etc.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photos_inspection_id'), 'photos', ['inspection_id'], unique=False)
    op.create_index(op.f('ix_photos_tenant_id'), 'photos', ['tenant_id'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inspection_id', sa.UUID(), nullable=False),
    sa.Column('damage_type', sa.String(length=100), nullable=False, comment='e.g. scratch, dent, crack, tear, discoloration'),
    sa.Column('location_description', sa.String(length=500), nullable=False, comment='Human-readable location of the damage on the asset'),
    sa.Column('severity', sa.Enum('MINOR', 'MODERATE', 'MAJOR', 'SEVERE', name='damage_severity', create_constraint=True), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False, comment='AI confidence 0-100'),
    sa.Column('ai_reasoning', sa.Text(), nullable=True, comment='Explanation from the AI model about the finding'),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'REJECTED', name='finding_status', create_constraint=True), nullable=False),
    sa.Column('before_photo_id', sa.UUID(), nullable=True),
    sa.Column('after_photo_id', sa.UUID(), nullable=True),
    sa.Column('bounding_box', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='{"x": int, "y": int, "width": int, "height": int} in pixels'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['after_photo_id'], ['photos.id'], ),
    sa.ForeignKeyConstraint(['before_photo_id'], ['photos.id'], ),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_inspection_id'), 'findings', ['inspection_id'], unique=False)
    op.create_index(op.f('ix_findings_tenant_id'), 'findings', ['tenant_id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('finding_id', sa.UUID(), nullable=False),
    sa.Column('inspection_id', sa.UUID(), nullable=False),
    sa.Column('feedback_type', sa.Enum('TRUE_POSITIVE', 'FALSE_POSITIVE', 'FALSE_NEGATIVE', 'SEVERITY_ADJUSTED', 'LOCATION_CORRECTED', name='feedback_type', create_constraint=True), nullable=False),
    sa.Column('operator_id', sa.UUID(), nullable=False),
    sa.Column('operator_notes', sa.Text(), nullable=True),
    sa.Column('corrected_damage_type', sa.String(length=100), nullable=True),
    sa.Column('corrected_severity', sa.String(length=50), nullable=True),
    sa.Column('corrected_location', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_finding_id'), 'feedback', ['finding_id'], unique=False)
    op.create_index(op.f('ix_feedback_inspection_id'), 'feedback', ['inspection_id'], unique=False)
    op.create_index(op.f('ix_feedback_tenant_id'), 'feedback', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_tenant_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_inspection_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_finding_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_findings_tenant_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_inspection_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_photos_tenant_id'), table_name='photos')
    op.drop_index(op.f('ix_photos_inspection_id'), table_name='photos')
    op.drop_table('photos')
    op.drop_index(op.f('ix_inspections_tenant_id'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_rental_session_id'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_asset_id'), table_name='inspections')
    op.drop_table('inspections')
    op.drop_index(op.f('ix_rental_sessions_tenant_id'), table_name='rental_sessions')
    op.drop_index(op.f('ix_rental_sessions_asset_id'), table_name='rental_sessions')
    op.drop_table('rental_sessions')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_repair_cost_lookups_tenant_id'), table_name='repair_cost_lookups')
    op.drop_table('repair_cost_lookups')
    op.drop_index(op.f('ix_model_metrics_tenant_id'), table_name='model_metrics')
    op.drop_table('model_metrics')
    op.drop_index(op.f('ix_assets_tenant_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_identifier'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
